# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SENIOR PROJECT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SENIOR PROJECT
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'RealmSwift'
pod 'Firebase/Analytics'
pod 'Firebase/AdMob'
pod 'MBProgressHUD', '~> 1.1.0'

  target 'SENIOR PROJECTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SENIOR PROJECTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
